name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: alirezabg18/hengampilotfinal1:latest

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
        cat ~/.ssh/id_rsa.pub
        ssh-keyscan -H 188.121.99.72 >> ~/.ssh/known_hosts
    - name: Debug SSH Setup
      run: |
        ls -la ~/.ssh
        cat ~/.ssh/known_hosts
        ssh -vvv ubuntu@188.121.99.72 "exit"  
    - name: Deploy to Server
      run: |
        ssh ubuntu@188.121.99.72 "cd /path/to/project && git pull && ./deploy-script.sh"