name: Continuous Deployment

on:
  push:
    branches:
      - main # این workflow روی شاخه main اجرا می‌شود
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # مرحله 1: دریافت کدهای پروژه
    - name: Checkout repository
      uses: actions/checkout@v4

    # مرحله 2: لاگین به DockerHub (اگر از Docker استفاده می‌کنید)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # مرحله 3: ساخت Docker Image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: alirezabg18/hengampilotfinal1:latest

    # مرحله 4: استقرار برنامه (Deployment)
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    
         # Generate a public key from the private key
        ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
    
        # Check the fingerprint of the public key
        ssh-keygen -l -f ~/.ssh/id_rsa.pub

        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H 188.121.111.56 >> ~/.ssh/known_hosts
    - name: Debug SSH Setup
      run: |
        ls -la ~/.ssh
        cat ~/.ssh/id_rsa
        cat ~/.ssh/known_hosts
        ssh -vvv ubuntu@188.121.111.56 "exit"

    - name: Deploy to Server
      run: |
        ssh ubuntu@188.121.111.56 "cd /path/to/project && git pull && ./deploy-script.sh"