name: Continuous Deployment

on:
  push:
    branches:
      - main # این workflow روی شاخه main اجرا می‌شود
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # مرحله 1: دریافت کدهای پروژه
    - name: Checkout repository
      uses: actions/checkout@v4

    # مرحله 2: لاگین به DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # مرحله 3: ساخت Docker Image و ارسال به DockerHub
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: alirezabg18/hengampilotfinal1:latest

    # مرحله 4: استقرار برنامه (Deployment)
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H 188.121.111.56 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh ubuntu@188.121.111.56 << 'EOF'
          set -e  # اگر خطایی رخ دهد، اجرای دستورات متوقف می‌شود
          cd Hengampilot-front/frontend || { echo "Error: Directory not found!"; exit 1; }
          git stash
          git pull

          # حذف کانتینر قدیمی در صورت وجود
          docker stop hengampilot-container || true
          docker rm hengampilot-container || true
          docker rmi alirezabg18/hengampilotfinal1:latest || true

          # اجرای Docker
          docker pull alirezabg18/hengampilotfinal1:latest
          docker run -d --name hengampilot-container -p 80:80 alirezabg18/hengampilotfinal1:latest
        EOF
