name: Continuous Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    # مرحله 1: دریافت کدهای پروژه
    - name: Checkout repository
      uses: actions/checkout@v4

    # مرحله 2: لاگین به DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # مرحله 3: ساخت و ارسال Docker Image به DockerHub
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: alirezabg18/hengampilotfinal1:latest

    # مرحله 4: استقرار برنامه روی سرور
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H 188.121.111.56 >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh ubuntu@188.121.111.56 << 'EOF'
          set -e  # متوقف کردن اسکریپت در صورت بروز خطا
          cd Hengampilot-front/frontend || { echo "Error: Directory not found!"; exit 1; }
          git stash
          git pull

          # ورود به DockerHub روی سرور
          echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          # بررسی و حذف کانتینر قبلی در صورت وجود
          if [ "$(sudo docker ps -aq -f name=frontend)" ]; then
            echo "Stopping and removing existing container..."
            sudo docker stop frontend || true
            sudo docker rm -f frontend || true
          fi

          # حذف ایمیج قدیمی
          sudo docker rmi -f alirezabg18/hengampilotfinal1:latest || true

          # دانلود و اجرای ایمیج جدید از DockerHub
          docker pull alirezabg18/hengampilotfinal1:latest
          docker run -d --name frontend -p 3000:3000 alirezabg18/hengampilotfinal1:latest
        EOF
